<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ass\\XmlSecurity' => array($vendorDir . '/ass/xmlsecurity/src'),
    'WebDriver' => array($vendorDir . '/instaclick/php-webdriver/lib'),
    'PHPMD\\' => array($vendorDir . '/phpmd/phpmd/src/main/php'),
    'Nelmio\\ApiDocBundle' => array($vendorDir . '/oro/api-doc-bundle'),
    'JsonpCallbackValidator' => array($vendorDir . '/willdurand/jsonp-callback-validator/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
    'Gaufrette' => array($vendorDir . '/knplabs/gaufrette/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Behat\\MinkExtension' => array($vendorDir . '/friends-of-behat/mink-extension/src'),
    'Behat\\Gherkin' => array($vendorDir . '/behat/gherkin/src'),
    'BeSimple\\SoapCommon' => array($vendorDir . '/besimple/soap-common'),
    'BeSimple\\SoapClient' => array($vendorDir . '/besimple/soap-client'),
);
