version: '3.7'
services:
  web:
    container_name: ${PROJECT_NAME}_WEB
    image: nginx:latest
    restart: always
    volumes:
      #Set default configuration to nginx  
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      # share projet folder with nginx
      - .:/var/www/app
    labels:
      # permet de créer un routeur Traefik 
      - "traefik.enable=true"
      - "traefik.http.services.symfony_poc.loadbalancer.server.port=80"
      - "traefik.http.routers.symfony_poc.rule=Host(`symofny-poc.groupe-pop.eu`)"
      - "traefik.http.routers.symfony_poc.entrypoints=websecure"
      - "traefik.http.routers.symfony_poc.tls.certresolver=myhttpchallenge"
    env_file:
      - .env
    networks:
      - traefik-proxy
  php:
    container_name: ${PROJECT_NAME}_PHP
    networks:
      - traefik-proxy
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: '${USER_ID:-1000}'
        GROUP_ID: '${GROUP_ID:-1000}'
        USER: '${USER:-User}'

    volumes:
      - .:/var/www/app
    ports:
      - ${BACK_PORT}:8000
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}_MYSQL
    command: --max_allowed_packet=130023424
    networks:
      - traefik-proxy
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
networks:
  traefik-proxy:
    external: true
volumes:
  mysqldata: {}
